### ISSUE TITLE
Guidance on which parser to choose?

### ISSUE THREAD

**Issue by KastanDay** [ramanathanlab/pdfwf#20]
### Describe the Request

Hi, I'm a big fan. I was referenced to y'all via Robert Underwood. 

My question is: which parser should I choose for which style of PDFs? Can you offer guidance here? 

Say I have standard academic PDFs, which parser should I use? 
What about PDFs of blog posts? 
Financial // business admin PDFs? 

Thanks for any help, 
Kastan

**Comment by 7shoe** [comment]
Hey Kastan,

Thank you. A subsection on how to [choose a parser](https://github.com/ramanathanlab/pdfwf?tab=readme-ov-file#choosing-a-parser-april-2024) has been added. In a nutshell, your choice will depend on how you balance accuracy and speed. 

Best,
Carlo
